# Generated by Django 4.2 on 2023-04-19 01:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Baby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                (
                    "birth_weight",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2500),
                            django.core.validators.MaxValueValidator(5000),
                        ]
                    ),
                ),
                (
                    "birth_length",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(75),
                        ]
                    ),
                ),
                (
                    "current_percentile",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "weight",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2500),
                            django.core.validators.MaxValueValidator(5000),
                        ]
                    ),
                ),
                (
                    "length",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(200),
                        ]
                    ),
                ),
                (
                    "z_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "percentile",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "baby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.baby"
                    ),
                ),
            ],
        ),
    ]
