# Generated by Django 4.2 on 2023-04-20 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_baby_options_baby_current_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baby",
            name="current_weight",
            field=models.IntegerField(
                blank=True,
                default=models.IntegerField(
                    validators=[
                        django.core.validators.MinValueValidator(2500),
                        django.core.validators.MaxValueValidator(5000),
                    ]
                ),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2500),
                    django.core.validators.MaxValueValidator(5000),
                ],
            ),
        ),
    ]
