# Generated by Django 4.2 on 2023-04-20 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_baby_current_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="length",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
    ]
