# Generated by Django 4.2 on 2023-04-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_baby_age_in_months"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baby",
            name="birth_weight",
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name="baby",
            name="current_weight",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="weight",
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
