# Generated by Django 4.2 on 2023-04-20 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_baby_birth_weight_alter_baby_current_weight_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="z_score",
        ),
    ]
