# Generated by Django 4.2 on 2023-04-21 01:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_record_z_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ("-date",)},
        ),
    ]
